### ISSUE TITLE
Tool to estimate pith offset distance and ring count

### ISSUE THREAD

**Issue by dendrodan** [UMN-LATIS/leaflet-treering#132]
Several users have requested a dynamic tool to estimate the number of rings missing when an increment core does not include pith. This is an infamously fraught estimation. Nevertheless, it is important for a number of analytics, including regional curve standardization and basal area increment. So, I capitulate. 

For simplicity, we will start with the Duncan 1989 approach (see screenshot and attached manuscript pdf). Later, we might consider an approach of visualization with concentric rings/adjustable growth rate, akin to the analog transparency approach.

We can add the tool as a new button under the edit menu (need to select icon). When that tool is selected, a popout/dialogue box would appear and provide the user with guidance and results, with option to implement adjustment to dating. The values for the estimated pith offset distance and the number of missing rings could be displayed in the bottom row metadata banner. 

Metadata banner example: CHC01A | 1816 – 2015 | Pith offset estimate 5.2mm, 7.2 years | DendroElevator developed at the University of Minnesota

Dialogue box contents example:
**Estimate Distance to Pith & Missing Rings (vis a vis Duncan 1989)
Instructions:**
[Graphical rendition of Duncan Figure 1]
1. Measure width of arc (L) by placing two points
2. Measure height of arc (h) by placing two points
3. Estimate growth rate for missing rings based on how many years? [text box with up/down arrows, similar to providing dating year value].

**Results:**
1. Estimated distance to pith = _____mm
2. Estimated number of rings missing = _____years

**Apply results to adjust dating of measured rings?** 
- [x] Yes
- [ ] No

![Screen Shot 2022-05-18 at 4 46 15 PM](https://user-images.githubusercontent.com/68042200/169163594-f1864bff-23a7-48c0-a168-99ad54385215.png)

[Duncan_1989_GeometricPithOffsetEstimation.pdf](https://github.com/UMN-LATIS/leaflet-treering/files/8721171/Duncan_1989_GeometricPithOffsetEstimation.pdf)

**Comment by thorn573** [comment]
Implemented 8/13/2024
