### ISSUE TITLE
adding points prior to origin of measurement time series

### ISSUE THREAD

**Issue by danjcrawford** [UMN-LATIS/leaflet-treering#30]
just noticed another issue crop up. went to add a point at the beginning of a series and it populated as “year undefined.” as such, the dating tool won’t work on this point.
![Screen Shot 2020-07-19 at 11 24 22 AM](https://user-images.githubusercontent.com/68510690/87879949-79527f00-c9b3-11ea-822c-ddf9db379584.png)

**Comment by dendrodan** [comment]
Add a point tool was designed to add a point between two existing points, not to append measurements to the start of the cumulative directional path. For adding just a few, simply stick them in line after the first and move around.

For appending longer sequences of points ahead of the first one, we will consider some sort of "insert measurements before first point" version of the "create a measurable point." A few times when I wanted to add a long sequence of points before the first, I opted to start over, which is frustrating for a long time series.

**Comment by dendrodan** [comment]
Now that we have the ability to convert points to start points, the user can hack this issue without much hassle. Closing.
