### ISSUE TITLE
Change how cut tool works.

### ISSUE THREAD

**Issue by thorn573** [UMN-LATIS/leaflet-treering#48]
Cut tool removes all points before or after (depending on where second point selection is).

Change to remove points within click bounds.

**Comment by dendrodan** [comment]
This could be nice functionality to add, if the add points with h bar tool can be overhauled to insert a new series of consecutive points (segment) between two existing segments with dating outcomes as desired by user. 

Until then, I think this might generate an undesirably complicated functionality that isn’t one we’d need that often.

**Comment by dendrodan** [comment]
Great work @gracehansen0099 handling this, now cuts all points from first point selected to second point selected. User can also now convert an existing point into a new start point, breaking the segment path. Happy campers all around. and undo works too, thanks @thorn573
